:toc:
:toclevels: 4
:toc-placement!:

= ArchUnit Spring Integration

The ArchUnit Spring Integration provides predefined https://github.com/TNG/ArchUnit[ArchUnit] rules for https://spring.io/projects[Spring] applications.

toc::[]

== Overview

The <<builtin-rules,built-in rules>> help you to avoid typical problems when developing Spring applications that would otherwise lead to unexpected behavior.

You can easily define your own rules using the built-in predicates and conditions.

== Getting Started

This library is available via https://central.sonatype.com/artifact/de.rweisleder/archunit-spring[Maven Central].
The library expects that the required dependencies for Spring and ArchUnit are already declared.

Maven:
[source,xml]
----
<dependency>
    <groupId>de.rweisleder</groupId>
    <artifactId>archunit-spring</artifactId>
    <version>1.1.0</version>
    <scope>test</scope>
</dependency>
----

Gradle:
[source]
----
testImplementation 'de.rweisleder:archunit-spring:1.1.0'
----

[#builtin-rules]
== Built-In Rules and Predicates

=== Spring Annotations

One key element of maintainable Spring applications is the https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model[Spring Annotation Model].
Essentially, it is about composable annotations using meta-annotations and aliases for annotation attributes, enhancing readability and reducing boilerplate code.

For example, the annotation `@GetMapping` is a shorthand for `@RequestMapping(method = RequestMethod.GET)`:
[source,java]
----
@GetMapping("/example")
// is the same as
@RequestMapping(method = RequestMethod.GET, path = "/example")
----

The standard `annotatedWith` and `metaAnnotatedWith` methods in ArchUnit are not sufficient for this use case, as they do not fully capture the way Spring evaluates these annotations.
Therefore, we have introduced a custom predicate `springAnnotatedWith` that mirrors Spring's annotation processing behavior, ensuring accurate rule enforcement.

As an example, this rule enforces all methods annotated with `@RequestMapping` (or `@GetMapping`, `@PostMapping` etc.) to be declared in classes annotated with `@Controller` (or `@RestController` etc.):
[source,java]
----
import static de.rweisleder.archunit.spring.SpringAnnotationPredicates.springAnnotatedWith;

methods()
    .that(are(springAnnotatedWith(RequestMapping.class)))
    .should().beDeclaredInClassesThat(are(springAnnotatedWith(Controller.class)));
----

As a more complex example, this rule enforces all paths in `@RequestMapping` (or `@GetMapping`, `@PostMapping` etc.) annotations to be lower-case:
[source,java]
----
methods()
    .that(
        are(springAnnotatedWith(RequestMapping.class)
            .as("annotated with @RequestMapping (or @GetMapping, @PostMapping etc.)"))
    )
    .should(
        be(springAnnotatedWith(RequestMapping.class,
            describe("@RequestMapping(path=<lower-case>)",
                requestMapping -> Arrays.stream(requestMapping.path()).allMatch(path -> path.toLowerCase().equals(path))))
        ).as("have path containing only lowercase characters")
    );
----

=== Spring Framework

==== SpringAsyncRules

===== Rule AsyncMethodsAreProxyable

The rule `SpringAsyncRules.AsyncMethodsAreProxyable` ensures that Spring can create proxies for methods that are annotated with `@Async` or `@ Asynchronous` (directly or at class level).

The easiest way to fulfill this rule is to make these methods public and not final and the bean classes containing these methods also not final.

[source,java]
----
@Service
public class HelloService {

    @Async // violation because the method is final
    public final void calculateHelloMessage() {
        // ...
    }

    @Async // good
    public void calculateHelloMessage() {
        // ...
    }
}
----

If Spring can not create a proxy for a method, this can lead to an exception when starting the context or to unexpected behavior when calling the method during runtime.

===== Rule AsyncMethodsHaveSuitableReturnType

The rule `SpringAsyncRules.AsyncMethodsHaveSuitableReturnType` ensures that methods annotated with `@Async` or `@Asynchronous` (directly or at class level) have a suitable return type.

It is most convenient that such methods return `void` or an object implementing `java.util.concurrent.Future`.

[source,java]
----
@Service
public class HelloService {

    @Async // violation because Spring discards the return value
    public String createHelloMessage() {
        // ...
    }

    @Async // good
    public Future<String> createHelloMessage() {
        // ...
    }
}
----

If such methods have other return types, Spring may discard the return value or calling such a method may lead to an exception.

===== Rule AsyncMethodsNotCalledFromSameClass

The rule `SpringAsyncRules.AsyncMethodsNotCalledFromSameClass` ensures that methods annotated with `@Async` or `@Asynchronous` (directly or at class level) are not called from within the same class.
Such internal calls bypass Spring's proxy mechanism, causing the intended asynchronous behavior to be ignored.

[source,java]
----
@Service
public class HelloService {

    public void sendHelloMessage() {
        Future<String> helloText = createHelloText(); // violation, because it's ambiguous if this method call is asynchronous or not (hint: it's synchronous)
    }

    @Async
    public Future<String> createHelloText() {
        // ...
    }
}
----

This rule should only be used if asynchronous method execution is used in proxy mode (which is the default mode), see the `@EnableAsync` annotation.

===== Rule EnableAsyncIsPresentIfAsyncMethodsExist

The rule `SpringAsyncRules.EnableAsyncIsPresentIfAsyncMethodsExist` ensures that the application contains a class annotated with `@EnableAsync` if any class contains a method annotated with `@Async`.
The annotations for asynchronous method execution would have no effect if there is no configuration class annotated with `@EnableAsync`.

[source,java]
----
@Configuration
@EnableAsync
public class AsyncConfiguration {
    // ...
}

@Service
public class HelloService {

    @Async
    public Future<String> createHelloMessage() {
        // ...
    }
}
----

The rule has no effect if no method annotated with `@Async` exists.

==== SpringCacheRules

===== Rule CacheableMethodsAreProxyable

The rule `SpringCacheRules.CacheableMethodsAreProxyable` ensures that Spring can create proxies for methods that are annotated with `@Cacheable`.

The easiest way to fulfill this rule is to make these methods public and not final and the bean classes containing these methods also not final.

[source,java]
----
@Service
public class HelloService {

    @Cacheable("helloMessage") // violation because the method is final
    public final String calculateHelloMessage() {
        // ...
    }

    @Cacheable("helloMessage") // good
    public String calculateHelloMessage() {
        // ...
    }
}
----

If Spring can not create a proxy for a method, this can lead to an exception when starting the context or to unexpected behavior when calling the method during runtime.

===== Rule CacheableMethodsNotCalledFromSameClass

The rule `SpringCacheRules.CacheableMethodsNotCalledFromSameClass` ensures that methods annotated with `@Cacheable` are not called from within the same class.
Such internal calls bypass Spring's proxy mechanism, causing the intended caching behavior to be ignored.

[source,java]
----
@Service
public class HelloService {

    public String calculateHelloMessage() {
        String helloRecipients = calculateHelloRecipients(); // violation, because it's ambiguous if this method call goes through the cache or not (hint: it ignores the cache)
    }

    @Cacheable("helloRecipients")
    public String calculateHelloRecipients() {
        // ...
    }
}
----

This rule should only be used if caching is used in proxy mode (which is the default mode), see the `@EnableCaching` annotation.

===== Rule EnableCachingIsPresentIfCacheableMethodsExist

The rule `SpringCacheRules.EnableCachingIsPresentIfCacheableMethodsExist` ensures that the application contains a class annotated with `@EnableCaching` if any class contains a method annotated with `@Cacheable`.
The annotation for caching would have no effect if there is no configuration class annotated with `@EnableCaching`.

[source,java]
----
@Configuration
@EnableCaching
public class CachingConfiguration {
    // ...
}

@Service
public class HelloService {

    @Cacheable("helloMessage")
    public String calculateHelloMessage() {
        // ...
    }
}
----

The rule has no effect if no method annotated with `@Cacheable` exists.

==== SpringComponentPredicates

The class `SpringComponentPredicates` contains predefined predicates to match the different Spring stereotypes like `@Controller`, `@Service` and `@Repository`.

==== SpringComponentRules

===== Rule DependenciesOfControllers

The rule `SpringComponentRules.DependenciesOfControllers` ensures that all controller classes only depend on service classes or repository classes.
They should not depend on other controller classes or configuration classes.

[source,java]
----
@Controller
public class HelloController {

    HelloService helloService; // good (if annotated with @Service)

    HelloRepository helloRepository; // good (if annotated with @Repository)

    GoodbyeController goodbyeController; // violation (if annotated with @Controller)

    HelloConfiguration helloConfiguration; // violation (if annotated with @Configuration)
}
----

===== Rule DependenciesOfServices

The rule `SpringComponentRules.DependenciesOfServices` ensures that all service classes only depend on other service classes or repository classes.
They should not depend on controller classes or configuration classes.

[source,java]
----
@Service
public class HelloService {

    HelloRepository helloRepository; // good (if annotated with @Repository)

    GoodbyeService goodbyeService; // good (if annotated with @Service)

    HelloController helloController; // violation (if annotated with @Controller)

    HelloConfiguration helloConfiguration; // violation (if annotated with @Configuration)
}
----

===== Rule DependenciesOfRepositories

The rule `SpringComponentRules.DependenciesOfRepositories` ensures that all repository classes only depend on other repository classes.
They should not depend on controller classes, service classes, or configuration classes.

[source,java]
----
@Repository
public class HelloRepository {

    GoodbyeRepository goodbyeRepository; // good (if annotated with @Repository)

    HelloService helloService; // violation (if annotated with @Service)

    HelloController helloController; // violation (if annotated with @Controller)

    HelloConfiguration helloConfiguration; // violation (if annotated with @Configuration)
}
----

==== SpringControllerRules

===== Rule ControllerNameWithoutRequestMapping

The rule `SpringControllerRules.ControllerNameWithoutRequestMapping` checks that named controllers (`@Controller` or `@RestController` etc.) are also annotated with `@RequestMapping` to avoid misinterpretation of the name as a path mapping.

Consider the following example:
[source,java]
----
@RestController("/hello")
class HelloController {

    @GetMapping
    String hello() {
        return "Hello World";
    }
}
----

At first glance, this looks correct.
However, a request to `GET /hello` would return HTTP 404.
The developer probably intended to write:

[source,java]
----
@RestController
@RequestMapping("/hello")
class HelloController {

    @GetMapping
    String hello() {
        return "Hello World";
    }
}
----

If developers want to assign a bean name to a controller, it is recommended to clearly separate the name from the path.

[source,java]
----
@RestController("hello")
@RequestMapping("/hello")
class HelloController {
    // ...
}
----

==== SpringScheduledRules

===== Rule EnableSchedulingIsPresentIfScheduledMethodsExist

The rule `SpringScheduledRules.EnableSchedulingIsPresentIfScheduledMethodsExist` ensures that the application contains a class annotated with `@EnableScheduling` if any class contains a method annotated with `@Scheduled`.
This annotation would have no effect if there is no configuration class annotated with `@EnableScheduling`.

[source,java]
----
@Configuration
@EnableScheduling
public class SchedulingConfiguration {
    // ...
}

@Service
public class HelloService {

    @Scheduled(/* ... */)
    public void sendHelloMessages() {
        // ...
    }
}
----

The rule has no effect if no method annotated with `@Scheduled` exists.

=== Spring Retry

==== SpringRetryRules

===== Rule RetryableMethodsAreProxyable

The rule `SpringRetryRules.RetryableMethodsAreProxyable` ensures that Spring can create proxies for methods that are annotated with `@Retryable`.

The easiest way to fulfill this rule is to make these methods public and not final and the bean classes containing these methods also not final.

If Spring can not create a proxy for a method, this can lead to an exception when starting the context or to unexpected behavior when calling the method during runtime.

[source,java]
----
@Service
public class HelloService {

    @Retryable // violation because the method is final
    public final String calculateHelloMessage() {
        // ...
    }

    @Retryable // good
    public String calculateHelloMessage() {
        // ...
    }
}
----

===== Rule RetryableMethodsNotCalledFromSameClass

The rule `SpringRetryRules.RetryableMethodsNotCalledFromSameClass` ensures that methods annotated with `@Retryable` are not called from within the same class.
Such internal calls bypass Spring's proxy mechanism, causing the intended retry behavior to be ignored.

[source,java]
----
@Service
public class HelloService {

    public String calculateHelloMessage() {
        String helloRecipients = calculateHelloRecipients(); // violation, because it's ambiguous if this method call will be retried on exception or not (hint: it will not be retried)
        // ...
    }

    @Retryable
    public String calculateHelloRecipients() {
        // ...
    }
}
----

This rule should only be used if retrying is used in proxy mode (which is the default mode), see the `@EnableRetry` annotation.

===== Rule EnableRetryIsPresentIfRetryableMethodsExist

The rule `SpringRetryRules.EnableRetryIsPresentIfRetryableMethodsExist` ensures that the application contains a class annotated with `@EnableRetry` if any class contains a method annotated with `@Retryable`.
The annotation for retry would have no effect if there is no configuration class annotated with `@EnableRetry`.

[source,java]
----
@Configuration
@EnableRetry
public class RetryConfiguration {
    // ...
}

@Service
public class HelloService {

    @Retryable
    public String calculateHelloMessage() {
        // ...
    }
}
----

The rule has no effect if no method annotated with `@Retryable` exists.

=== Spring Boot

==== SpringBootRules

===== Rule AllTypesInApplicationPackage

The rule `SpringBootRules.AllTypesInApplicationPackage` checks that all classes are located in the same package or a sub-package of the application class.
The application class is the one annotated with `@SpringBootApplication` or `@SpringBootConfiguration`.

===== Rule ApplicationHasOnlyOneSpringBootConfiguration

A Spring Boot application should have exactly one class annotated with `@SpringBootConfiguration`, which is typically inherited from `@SpringBootApplication`.
The rule `SpringBootRules.ApplicationHasOnlyOneSpringBootConfiguration` checks that there is at most one such class within the analyzed codebase.

== Compatibility and Support

=== Open Source Edition

For each release of this project, compatibility is confirmed with the most recent version of ArchUnit and the minor versions of _Spring projects with OSS support_ available at that release's time.

[cols="1,1,1"]
|===
| | ArchUnit Spring version | Confirmed Compatibility

.2+| ArchUnit
| 1.1.0 | 1.4.0
| 1.0.0 | 1.3.0

.2+| Spring Boot
| 1.1.0 | 3.3, 3.4
| 1.0.0 | 3.1, 3.2, 3.3
|===

Compatibility with other versions is possible, but not guaranteed.

New features, bug fixes, and releases are provided on a best-effort basis, as my time permits, without any particular priority.

=== Enterprise Edition

The Enterprise Edition is compatible with the most recent version of ArchUnit and the minor versions of _Spring projects with enterprise support_ available at that release's time.

[cols="1,1,1"]
|===
| | ArchUnit Spring version | Confirmed Compatibility

.2+| ArchUnit
| 1.1.0 | 1.4.0
| 1.0.0 | 1.3.0

.2+| Spring Boot
| 1.1.0 | 2.7, 3.1, 3.2, 3.3, 3.4
| 1.0.0 | 2.7, 3.0, 3.1, 3.2, 3.3
|===

The Enterprise Edition also offers the following benefits:

* Commercial support
* Warranty and liability coverage

For a detailed comparison of Open Source and Enterprise Edition and pricing, please https://arcndev.com/archunit-spring/[visit our homepage].
